version: '3.1'

services:
    # Change this if your want use your own application.
    # It's very important expose your application in port 5442
    # and use the http protocol.
    app:
        image: ${OV_CALL_IMAGE}
        restart: on-failure
        env_file:
            - .env
        ports:
            - "5442:80"
        environment: 
            - OPENVIDU_URL=https://${OPENVIDU_DOMAIN_OR_PUBLIC_IP}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
