filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
- add_host_metadata: ~

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output:
  elasticsearch:
    hosts: ["elasticsearch:9200"]
    indices:
      - index: "filebeat-openvidu-server-%{[host.hostname]}"
        when.or:
          - contains:
              container.image.name: openvidu/openvidu-server-pro
      - index: "filebeat-redis-%{[host.hostname]}"
        when.or:
          - contains:
              container.image.name: redis
      - index: "coturn-%{[host.hostname]}"
        when.or:
          - contains:
              container.image.name: openvidu/openvidu-coturn

logging.json: true
logging.metrics.enabled: false