version: '3.1'

services:
    kms:
        image: ${KMS_IMAGE}
        restart: always
        network_mode: host
        env_file:
            - .env
        ulimits:
            core: -1
        environment:
            - KMS_MIN_PORT=${KMS_MIN_PORT}
            - KMS_MAX_PORT=${KMS_MAX_PORT}
            - GST_DEBUG=${KMS_DEBUG_LEVEL:-}
        volumes:
            - /opt/openvidu/recordings:/opt/openvidu/recordings
        
    nginx:
        image: openvidu/openvidu-proxy:1.0.0-beta2
        entrypoint: ["/bin/bash", "-c", "service nginx restart && tail -f /var/log/nginx/*.log"]
        restart: on-failure
        network_mode: host
        volumes:
            - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx_conf/kms-recorder.conf:/etc/nginx/conf.d/default.conf
            - /opt/openvidu/recordings:/opt/openvidu/recordings
    