#!/bin/bash

upgrade_media_node() {
  UPGRADE_SCRIPT_URL="https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/install_media_node_OVVERSION.sh"
  HTTP_STATUS=$(curl -s -o /dev/null -I -w "%{http_code}" ${UPGRADE_SCRIPT_URL//OVVERSION/$1})

  printf "  => Upgrading Media Node to '%s' version" "$1"

  if [ "$HTTP_STATUS" == "200" ]; then
    printf "\n    => Downloading and upgrading new version"
    printf "\n"

    curl --silent ${UPGRADE_SCRIPT_URL//OVVERSION/$1} | bash -s upgrade
  else
     printf "\n     =======¡ERROR!======="
     printf "\n     Media Node Version %s not exist" "$1"
     printf "\n"
     exit 0
  fi
}

usage() {
    printf "Usage: \n\t media_node [command]"
    printf "\n\nAvailable Commands:"
    printf "\n\tstart\t\tStart media node service"
    printf "\n\tstop\t\tStop media node service"
    printf "\n\trestart\t\tRestart media node service"
    printf "\n\tlogs\t\tShow media node logs"
    printf "\n\tupgrade\t\t\tUpgrade to the lastest Media Node version"
    printf "\n\tupgrade [version]\tUpgrade to the specific Media Node version"
    printf "\n\thelp\t\tShow help for media node command"
    printf "\n"
}

case $1 in

  start)
    docker-compose up -d
    docker-compose logs -f kms
    ;;

  stop)
    docker-compose down
    ;;

  restart)
    docker-compose down
    docker-compose up -d
    docker-compose logs -f kms
    ;;

  logs)
    docker-compose logs -f kms
    ;;

  upgrade)
    if [ -z "$2" ]; then
      UPGRADE_VERSION="latest"
    else
      UPGRADE_VERSION="$2"
    fi

    read -r -p "  You're about to update Media Node to '${UPGRADE_VERSION}' version. Are you sure? [y/N]: " response
        case "$response" in
        [yY][eE][sS]|[yY]) 
            upgrade_media_node "${UPGRADE_VERSION}"
            ;;
        *)
            exit 0
            ;;
    esac
    ;;

  *)
    usage
    ;;
esac
